" escape key remaping
noremap jk <esc>
inoremap jk <esc>
" pathogen
execute pathogen#infect()
syntax on 
filetype plugin indent on

" backup directories
set backupdir=./.backup,$HOME/.vim/backups,/tmp
set directory=./.backup,$HOME/.vim/backups,/tmp

set number 
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
augroup vimrcEx
au!
    autocmd FileType text setlocal textwidth=78
    autocmd BufRead *.asciidoc set tw=78 | :Voom asciidoc
    autocmd BufRead *.adoc set tw=78 | :Voom asciidoc
    autocmd BufRead *.md set tw=78 
    autocmd BufRead *.py set tw=79
    autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
augroup END 

let mapleader=','

inoremap <C-U> <C-G>u<C-U>

" reformat
noremap <leader>r mvgq}`v

noremap <leader>i :set rightleft!<cr>

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" navigation

noremap <C-n> :NERDTreeToggle<CR>
nnoremap <backspace> <C-u>
nnoremap <space> <C-D>
noremap <leader>l <C-w>l
noremap <leader>k <C-w>k
noremap <leader>j <C-w>j
noremap <leader>h <C-w>h
hi Pmenu ctermfg=8 ctermbg=0
hi PmenuSel ctermfg=6 ctermbg=0

" abbreviations
iabbrev adn and
iabbrev fo of

" bible functions 
function! BibleGen(mod, key)
    exe 'command -nargs=+' a:mod "let @h=system('diatheke -b" a:mod
                \"-o acv -k <args> | grep -v" a:mod "')"
    exe "inoremap ,".a:key '<space><Esc>"hd2B:'.a:mod '<C-R>h<CR>i<C-r>h'
    exe "xnoremap ,".a:key '"hd:'.a:mod '<C-R>h<CR>i<C-R>h<Esc>'
endfunction

call BibleGen('MorphGNT', 'gb')
call BibleGen('OSHB', 'hb')
